# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ImportadorGNSS
                                 A QGIS plugin
 Importa, filtra e projeta arquivos .pos gerados por receptores GNSS/RTK
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-09-09
        copyright            : (C) 2026 by Gabriel Aoki
        email                : glaoki@sp.gov.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Gabriel Aoki'
__date__ = '2026-09-09'
__copyright__ = '(C) 2026 by Gabriel Aoki'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ImportadorGNSS class from file ImportadorGNSS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gnss_pos_importer import ImportadorGNSSPlugin
    return ImportadorGNSSPlugin()
