# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ImportadorGNSS
                                 A QGIS plugin
 Importa, filtra e projeta arquivos .pos gerados por receptores GNSS/RTK
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-09-09
        copyright            : (C) 2026 by Gabriel Aoki
        email                : glaoki@sp.gov.br
 ***************************************************************************/
"""

__author__ = 'Gabriel Aoki'
__date__ = '2026-09-09'
__copyright__ = '(C) 2026 by Gabriel Aoki'
__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (QgsProcessingAlgorithm,
                       QgsProcessingParameterFile,
                       QgsProcessingParameterCrs,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterBoolean,
                       QgsProcessingParameterFeatureSink,
                       QgsCoordinateReferenceSystem,
                       QgsCoordinateTransform,
                       QgsFeature,
                       QgsGeometry,
                       QgsPointXY,
                       QgsFields,
                       QgsField,
                       QgsFeatureSink,
                       QgsWkbTypes)

class ImportadorGNSSAlgorithm(QgsProcessingAlgorithm):
    INPUT = 'INPUT'
    TARGET_CRS = 'TARGET_CRS'
    GEOM_TYPE = 'GEOM_TYPE'
    MAX_ERROR = 'MAX_ERROR'
    MIN_SATS = 'MIN_SATS'
    SMOOTH = 'SMOOTH'
    SMOOTH_ITER = 'SMOOTH_ITER'
    SMOOTH_OFFSET = 'SMOOTH_OFFSET'
    OUTPUT = 'OUTPUT'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return ImportadorGNSSAlgorithm()

    def name(self):
        return 'importarpos_pro'

    def displayName(self):
        return 'Importar Arquivo .pos (Modo Avançado)'

    def group(self):
        return 'Vetorização GNSS'

    def groupId(self):
        return 'vetorizacao_gnss'

    def shortHelpString(self):
        return "Importa .pos com filtros GNSS visíveis, cálculo automático de área/extensão e suavização."

    def initAlgorithm(self, config=None):
        self.addParameter(QgsProcessingParameterFile(
            self.INPUT, '1. Selecione o arquivo .pos', extension='pos'))

        self.addParameter(QgsProcessingParameterCrs(
            self.TARGET_CRS, '2. Sistema de Referência de Saída', 'EPSG:31982'))

        self.addParameter(QgsProcessingParameterEnum(
            self.GEOM_TYPE, '3. Tipo de Geometria de Saída', options=['Pontos', 'Linha', 'Polígono'], defaultValue=0))

        self.addParameter(QgsProcessingParameterNumber(
            self.MAX_ERROR, '4. FILTRO: Descartar pontos com erro posicional maior que (Metros) [0 = Desativar]', 
            type=QgsProcessingParameterNumber.Double, defaultValue=0.15, minValue=0.0))
            
        self.addParameter(QgsProcessingParameterNumber(
            self.MIN_SATS, '5. FILTRO: Descartar pontos com quantidade de satélites menor que [0 = Desativar]', 
            type=QgsProcessingParameterNumber.Integer, defaultValue=12, minValue=0))

        self.addParameter(QgsProcessingParameterBoolean(
            self.SMOOTH, '6. SUAVIZAÇÃO: Arredondar cantos (Apenas para Linha/Polígono)?', defaultValue=False))
        self.addParameter(QgsProcessingParameterNumber(
            self.SMOOTH_ITER, '↳ Iterações da Suavização (Recomendado: 3)', 
            type=QgsProcessingParameterNumber.Integer, defaultValue=3, minValue=1, maxValue=10))
        self.addParameter(QgsProcessingParameterNumber(
            self.SMOOTH_OFFSET, '↳ Deslocamento / Offset (Recomendado: 0.25)', 
            type=QgsProcessingParameterNumber.Double, defaultValue=0.25, minValue=0.01, maxValue=0.5))

        self.addParameter(QgsProcessingParameterFeatureSink(self.OUTPUT, 'Camada de Saída'))

    def processAlgorithm(self, parameters, context, feedback):
        input_file = self.parameterAsFile(parameters, self.INPUT, context)
        target_crs = self.parameterAsCrs(parameters, self.TARGET_CRS, context)
        geom_type_idx = self.parameterAsEnum(parameters, self.GEOM_TYPE, context)
        max_error = self.parameterAsDouble(parameters, self.MAX_ERROR, context)
        min_sats = self.parameterAsInt(parameters, self.MIN_SATS, context)
        apply_smooth = self.parameterAsBool(parameters, self.SMOOTH, context)
        smooth_iter = self.parameterAsInt(parameters, self.SMOOTH_ITER, context)
        smooth_offset = self.parameterAsDouble(parameters, self.SMOOTH_OFFSET, context)

        if geom_type_idx == 0:
            wkb_type = QgsWkbTypes.Point
        elif geom_type_idx == 1:
            wkb_type = QgsWkbTypes.LineString
        else:
            wkb_type = QgsWkbTypes.Polygon

        source_crs = QgsCoordinateReferenceSystem("EPSG:4674")
        transform = QgsCoordinateTransform(source_crs, target_crs, context.transformContext())

        fields = QgsFields()
        if geom_type_idx == 0: 
            fields.append(QgsField('Data', QVariant.String))
            fields.append(QgsField('Hora', QVariant.String))
            fields.append(QgsField('Altitude', QVariant.Double))
            fields.append(QgsField('Satelites', QVariant.Int))
            fields.append(QgsField('Erro_N_m', QVariant.Double))
            fields.append(QgsField('Erro_E_m', QVariant.Double))
        elif geom_type_idx == 1: 
            fields.append(QgsField('Extensao_m', QVariant.Double))
            fields.append(QgsField('Pts_Usados', QVariant.Int))
            fields.append(QgsField('Pts_Filtra', QVariant.Int))
        else: 
            fields.append(QgsField('Area_ha', QVariant.Double))
            fields.append(QgsField('Perim_m', QVariant.Double))
            fields.append(QgsField('Pts_Usados', QVariant.Int))
            fields.append(QgsField('Pts_Filtra', QVariant.Int))

        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT, context, fields, wkb_type, target_crs)

        def dms_para_dd(graus, minutos, segundos):
            dd = float(graus)
            if dd < 0: return dd - (float(minutos) / 60) - (float(segundos) / 3600)
            else: return dd + (float(minutos) / 60) + (float(segundos) / 3600)

        with open(input_file, 'r', encoding='utf-8', errors='ignore') as f:
            lines = f.readlines()

        total_lines = len(lines)
        step = 100.0 / total_lines if total_lines > 0 else 1
        
        pontos_validos = []
        qtd_total_rastreada = 0
        qtd_excluidos = 0

        for current, line in enumerate(lines):
            if feedback.isCanceled(): break
            if line.startswith('%'): continue

            partes = line.split()
            if len(partes) >= 15:
                qtd_total_rastreada += 1
                sats = int(partes[10])
                erro_n = float(partes[11])
                erro_e = float(partes[12])
                
                descartar_por_erro = (max_error > 0.0) and (erro_n > max_error or erro_e > max_error)
                descartar_por_sat = (min_sats > 0) and (sats < min_sats)
                
                if descartar_por_erro or descartar_por_sat:
                    qtd_excluidos += 1
                    continue

                lat = dms_para_dd(partes[2], partes[3], partes[4])
                lon = dms_para_dd(partes[5], partes[6], partes[7])
                
                pt = QgsPointXY(lon, lat)
                geom_pt = QgsGeometry.fromPointXY(pt)
                geom_pt.transform(transform) 
                
                if geom_type_idx == 0:
                    feat = QgsFeature(fields)
                    feat.setGeometry(geom_pt)
                    feat.setAttributes([partes[0], partes[1], float(partes[8]), sats, erro_n, erro_e])
                    sink.addFeature(feat, QgsFeatureSink.FastInsert)
                else:
                    pontos_validos.append(geom_pt.asPoint())

            feedback.setProgress(int(current * step))

        if geom_type_idx > 0 and len(pontos_validos) >= 2:
            if geom_type_idx == 2 and len(pontos_validos) >= 3:
                if pontos_validos[0] != pontos_validos[-1]:
                    pontos_validos.append(pontos_validos[0])
                geom_final = QgsGeometry.fromPolygonXY([pontos_validos])
            else:
                geom_final = QgsGeometry.fromPolylineXY(pontos_validos)

            if apply_smooth:
                geom_final = geom_final.smooth(smooth_iter, smooth_offset)

            feat = QgsFeature(fields)
            feat.setGeometry(geom_final)
            
            if geom_type_idx == 1:
                extensao = round(geom_final.length(), 2)
                feat.setAttributes([extensao, len(pontos_validos), qtd_excluidos])
            elif geom_type_idx == 2:
                area_ha = round(geom_final.area() / 10000.0, 4)
                perimetro = round(geom_final.length(), 2)
                feat.setAttributes([area_ha, perimetro, len(pontos_validos), qtd_excluidos])
                
            sink.addFeature(feat, QgsFeatureSink.FastInsert)

        feedback.pushInfo("=======================================")
        feedback.pushInfo("RELATÓRIO DE PROCESSAMENTO DO ARQUIVO .POS")
        feedback.pushInfo(f"-> Total de pontos lidos no arquivo: {qtd_total_rastreada}")
        feedback.pushInfo(f"-> Pontos DESCARTADOS pelos filtros: {qtd_excluidos}")
        if geom_type_idx > 0:
            feedback.pushInfo(f"-> Vértices utilizados no desenho final: {len(pontos_validos)}")
        feedback.pushInfo("=======================================")

        return {self.OUTPUT: dest_id}